/// GENERATED BY assets_scanner. DO NOT MODIFY BY HAND.
/// See more detail on https://github.com/littleGnAl/assets-scanner.
class R {
  static const package = 'netflix_clone';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/original_netflix1.png)
  static const images_original_netflix1 = 'assets/images/original_netflix1.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/thirty_nine.png)
  static const images_thirty_nine = 'assets/images/thirty_nine.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/icon.png)
  static const images_icon = 'assets/images/icon.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/original_netflix2.png)
  static const images_original_netflix2 = 'assets/images/original_netflix2.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/original_netflix3.png)
  static const images_original_netflix3 = 'assets/images/original_netflix3.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/three.png)
  static const images_three = 'assets/images/three.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/original_netflix4.png)
  static const images_original_netflix4 = 'assets/images/original_netflix4.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/fishbowl.png)
  static const images_fishbowl = 'assets/images/fishbowl.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/original_netflix5.png)
  static const images_original_netflix5 = 'assets/images/original_netflix5.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/ic_home.png)
  static const images_ic_home = 'assets/images/ic_home.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/poster.png)
  static const images_poster = 'assets/images/poster.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/tinder.png)
  static const images_tinder = 'assets/images/tinder.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/two.png)
  static const images_two = 'assets/images/two.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/ic_screen_mirror.png)
  static const images_ic_screen_mirror = 'assets/images/ic_screen_mirror.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/four.png)
  static const images_four = 'assets/images/four.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/ic_dot.png)
  static const images_ic_dot = 'assets/images/ic_dot.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/ic_new_and_popular.png)
  static const images_ic_new_and_popular = 'assets/images/ic_new_and_popular.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/avatar5.png)
  static const images_avatar5 = 'assets/images/avatar5.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/avatar4.png)
  static const images_avatar4 = 'assets/images/avatar4.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/love_you.png)
  static const images_love_you = 'assets/images/love_you.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/logo.png)
  static const images_logo = 'assets/images/logo.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/ic_search.png)
  static const images_ic_search = 'assets/images/ic_search.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/taxi_driver.png)
  static const images_taxi_driver = 'assets/images/taxi_driver.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/avatar3.png)
  static const images_avatar3 = 'assets/images/avatar3.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/five.png)
  static const images_five = 'assets/images/five.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/avatar2.png)
  static const images_avatar2 = 'assets/images/avatar2.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/one.png)
  static const images_one = 'assets/images/one.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/ic_download.png)
  static const images_ic_download = 'assets/images/ic_download.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/ic_play.png)
  static const images_ic_play = 'assets/images/ic_play.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/avatar1.png)
  static const images_avatar1 = 'assets/images/avatar1.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/ai_love_you.png)
  static const images_ai_love_you = 'assets/images/ai_love_you.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/forecasting.png)
  static const images_forecasting = 'assets/images/forecasting.png';

  /// ![](/Users/Dev/Flutter Project/netflix_clone/assets/images/cloy.png)
  static const images_cloy = 'assets/images/cloy.png';

// ignore_for_file: always_put_control_body_on_new_line,always_specify_types,annotate_overrides,avoid_annotating_with_dynamic,avoid_as,avoid_catches_without_on_clauses,avoid_returning_this,lines_longer_than_80_chars,omit_local_variable_types,prefer_expression_function_bodies,sort_constructors_first,test_types_in_equals,unnecessary_const,unnecessary_new,public_member_api_docs,constant_identifier_names,prefer_double_quotes
}
